name = "personality-spark-api"
main = "src/index.ts"
compatibility_date = "2025-07-18"
compatibility_flags = ["nodejs_compat"]

# Account details
account_id = "79c03e5169d22c2c869d0d3c80932187"

# Custom domains (when ready)
# routes = [
#   { pattern = "api.personalityspark.com/*", zone_name = "personalityspark.com" }
# ]

# D1 Database
[[d1_databases]]
binding = "DB"
database_name = "personality-spark-db"
database_id = "0e844e2c-54e1-4122-bab1-698fc86be2f6"

# KV Namespaces
[[kv_namespaces]]
binding = "SESSIONS"
id = "643c50b21e5d44aca5f49c84a509a40d"

[[kv_namespaces]]
binding = "CACHE"
id = "c79fa3abb6d949d5aa540373fbb9fe4a"

# R2 Storage
[[r2_buckets]]
binding = "MEDIA"
bucket_name = "personality-spark-media"

[[r2_buckets]]
binding = "BACKUPS"
bucket_name = "personality-spark-backups"

[[r2_buckets]]
binding = "FILES"
bucket_name = "personality-spark-files"

# Environment variables (use wrangler secret put for sensitive values)
[vars]
ENVIRONMENT = "production"
API_VERSION = "v1"
CORS_ORIGIN = "https://personalityspark.com"

# Queues (requires paid plan)
# [[queues.producers]]
# binding = "TASK_QUEUE"
# queue = "personality-spark-tasks"

# [[queues.consumers]]
# queue = "personality-spark-tasks"
# max_batch_size = 10
# max_batch_timeout = 30

# Development settings
[env.development]
name = "personality-spark-api-dev"
vars = { ENVIRONMENT = "development", CORS_ORIGIN = "*" }

[[env.development.d1_databases]]
binding = "DB"
database_name = "personality-spark-db"
database_id = "0e844e2c-54e1-4122-bab1-698fc86be2f6"

[[env.development.kv_namespaces]]
binding = "SESSIONS"
id = "643c50b21e5d44aca5f49c84a509a40d"

[[env.development.kv_namespaces]]
binding = "CACHE"
id = "c79fa3abb6d949d5aa540373fbb9fe4a"

[[env.development.r2_buckets]]
binding = "MEDIA"
bucket_name = "personality-spark-media"

[[env.development.r2_buckets]]
binding = "BACKUPS"
bucket_name = "personality-spark-backups"

[[env.development.r2_buckets]]
binding = "FILES"
bucket_name = "personality-spark-files"

# Staging environment
[env.staging]
name = "personality-spark-api-staging"
vars = { ENVIRONMENT = "staging", CORS_ORIGIN = "https://staging.personalityspark.com" }

[[env.staging.d1_databases]]
binding = "DB"
database_name = "personality-spark-db"
database_id = "0e844e2c-54e1-4122-bab1-698fc86be2f6"

[[env.staging.kv_namespaces]]
binding = "SESSIONS"
id = "643c50b21e5d44aca5f49c84a509a40d"

[[env.staging.kv_namespaces]]
binding = "CACHE"
id = "c79fa3abb6d949d5aa540373fbb9fe4a"

[[env.staging.r2_buckets]]
binding = "MEDIA"
bucket_name = "personality-spark-media"

[[env.staging.r2_buckets]]
binding = "BACKUPS"
bucket_name = "personality-spark-backups"

[[env.staging.r2_buckets]]
binding = "FILES"
bucket_name = "personality-spark-files"