name: Deploy Worker

on:
  push:
    branches:
      - main
    paths:
      - 'personality-spark-api/**'
      - 'apps/web/**'
      - '.github/workflows/deploy.yml'

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'apps/web/package-lock.json'
      
      - name: Install frontend dependencies
        working-directory: apps/web
        run: npm ci
      
      - name: Build frontend
        working-directory: apps/web
        run: npm run build
      
      - name: Copy bundle to API public directory
        run: cp apps/web/dist/bundle.js personality-spark-api/public/
      
      - name: Upload frontend artifacts
        uses: actions/upload-artifact@v4
        with:
          name: frontend-bundle
          path: personality-spark-api/public/bundle.js

  deploy:
    runs-on: ubuntu-latest
    needs: build-frontend
    steps:
      - uses: actions/checkout@v4
      
      - name: Download frontend artifacts
        uses: actions/download-artifact@v4
        with:
          name: frontend-bundle
          path: personality-spark-api/public/
      
      - name: Deploy to Cloudflare Workers
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          workingDirectory: 'personality-spark-api'
          command: deploy